### ISSUE TITLE
Can't locate object method "swig_ways_mask_get" via package "pqos::pqos_l3ca" at /usr/local/lib64/perl5/pqos.pm line 33.

### ISSUE THREAD

**Issue by davidlt** [01org/intel-cmt-cat#26] opened 2016-06-11 15:20 UTC
System details:
```
# swig -version

SWIG Version 2.0.10

Compiled with g++ [x86_64-redhat-linux-gnu]

Configured options: +pcre

# perl --version

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 29 registered patches, see perl -V for more detail)

# gcc -dumpversion
4.8.5

# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
```

I am running on Jun 10 commit (`43bc01e911b696f9d91299f9183ed5f859605ee1`).

It can be triggered by calling `./examples/perl/hello_world.pl` or `./lib/perl/test.pl`.

**Comment by tkanteck** [comment] 2016-06-13 10:38
Thanks for reporting the issue. We'll have a look into it shortly.

**Comment by tkanteck** [comment] 2016-06-14 09:57
We have tried to reproduce the problem with the commit above on our Fedora systems but we failed. Tested configs:
- Fedora 16, SWIG 2.0.4, PERL 5.14.3
- Fedora 21, SWIG 3.0.7, PERL 5.18.4
As we don't have access to CentOS 7.2 at the moment, extensive logs from compiling Perl interface and script execution could be useful. Could you clean the installation, build (capture logs), run (capture logs) and send the logs please?

**Comment by davidlt** [comment] 2016-06-14 10:56
I will try to reproduce it with clean and up to date CentOS 7.2 vagrant box.

**Comment by davidlt** [comment] 2016-06-15 11:33
Here is full content of `perl` directory after building + logs: http://davidlt.web.cern.ch/davidlt/vault/perl-intel-cmt-cat.tar.gz
```
612K    perl-intel-cmt-cat.tar.gz
```
`build.log` contains output from makefile which executed swig.

**Comment by wandralx** [comment] 2016-06-22 09:48
First of all, thank you for providing us with full content of perl directory (not just logs), it was really useful! 

It seems that the problem is that SWIG 2.x does not support C features used in libpqos code (nested anonymous union in pqos_l3ca).
I haven’t spotted that earlier as we use SWIG 3.x for development and testing.

Now that I know what the problem is, I have reproduced the issue on an older configuration (Fedora 16, SWIG 2.0.4, PERL 5.14.3)

Right now I am looking for workaround for that problem.

**Comment by tkanteck** [comment] 2016-06-27 14:18
Hi David,
Could you verify the above commit fixes problem on your system?
Thanks,
Tomasz

**Comment by davidlt** [comment] 2016-07-07 07:30
I can confirm that it now works on CentOS 7.2.1511 + SWIG 2.0.10

**Comment by tkanteck** [comment] 2016-07-07 09:01
Thanks for verifying David. I am closing the issue.

**Closed by tkanteck** 2016-07-07 09:01 UTC
